name: Build and publish multiversion documentation

on:
  push:
    branches: [ main, Build* ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout all branches
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx-multiversion sphinx-rtd-theme sphinxcontrib-mermaid ghp-import

      - name: Build multiversion docs
        run: |
          sphinx-multiversion source _build/html

      - name: Add root index.html to redirect to Build25
        run: |
          echo '<!DOCTYPE html><html><head><meta http-equiv="Refresh" content="0; url=Build25/index.html" /></head><body><p>Redirecting to Build25...</p></body></html>' > _build/html/index.html

      - name: Deploy using ghp-import
        run: |
          ghp-import -n -p -f build/html/main
